### ISSUE TITLE
Attestverwaltung verschieben

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#13]
Die Attestverwaltung (eintragen ob ein Attest eingereicht wurde) sollte nicht bei den Zulassungen/Anmeldungen sein, da diese Vor der Klausur relevant sind, die Atteste aber erst nach der Klausur.
Ich würde vorschlagen, die Atteste auf die selbe Seite zu setzen wie die Noten oder auf eine Extra-Seite.

**Comment by tynsh** [comment]
Ich finde die Variante toll, Atteste auf der gleichen Seite dazustellen wie die Noten. Erscheint mir logischer, da die Note effektiv ja durch ein Attest „ersetzt“ wird. Lass mich aber gerne von einer Extra Seite überzeugen.

**Comment by DieGoldeneEnte** [comment]
Die Atteste passen nur bedingt zu den Noten, da man das Attest meistens bekommt bevor man die Klausur korrigiert hat (nehme ich zumindest an).
Wenn man das Attest bei den Noten einträgt, hätte es den Vorteil, dass man eine bessere Übersicht hat.

Ich würde das letzendlich auch davon abhängig machen, was man bei Attesten alles angeben können soll. Herr Andrzejak den Wunsch geäußert hatte ein Datum mit dem Attest abzuspeichern. Das ist zur Zeit nicht möglich (zumindestens sehe ich es nicht in den Datenmodellen) und würde mehr Platz wegnehmen als ein einfacher Radio-Button.

**Comment by tynsh** [comment]
Ah, okay. Wie geschrieben, hab ich keine starke Meinung dazu.

Puh, ich bin mir nicht sicher ob man aus Datenschutzgründen ein Datum zur Abgabe des Attestes speichern darf. Was laut Prüfungsordnung relevant ist, ist nur ob ein Attest rechtzeitig eingereicht wurde. D.h. wenn ein Attest zu spät eingereicht wurde, ist man bei der Prüfung unentschuldigt abwesend. Dann gibt es ja auch keinen Bedarf das Attest einzutragen, da dieses ja irrelevant ist.

Hab ich da einen anderen Grund fürs Interesse am Abgabedatum eines Attestes übersehen?

**Comment by DieGoldeneEnte** [comment]
Ich kenne keinen Grund. Dann werde ich das erst einmal ohne Datum planen und Herr Andrzejak beim nächsten Treffen fragen.

**Comment by DieGoldeneEnte** [comment]
Die Atteste lassen sich nun auch aus dem (einfachen) Punkte eintragen heraus ändern. Damit kann man die Atteste nun an 2 Stellen ändern, was aber für die Übersicht deutlich verbessert, da man beim Punkte eintragen sehen kann wer ein Attest vorgelegt hat.
