### ISSUE TITLE
Tutoren Statistiken und Diagramme anzeigen

### ISSUE THREAD

**Issue by Pflegusch** [Philipp-g/muesli#26]
Statistiken und Diagramme für Tutoren anzeigen lassen. Der Tutor sollte hierbei auch auswählen können, ob er für alle Vorlesungsteilnehmer oder nur für seine Übungsgruppe Statistiken oder Diagramme sehen will. Die Statistiken sollten auch so angezeigt werden, dass die auf eine Bildschirmansicht passen.

**Comment by tynsh** [comment]
Statistiken für alle Vorlesungsteilnehmer sollten nur sichtbar sein, wenn die Vorlesungsoption „Tutorenrechte“ auf „Punkte aller Studierende editieren“ steht.
