### ISSUE TITLE
Intuitive Bedienung und Hilfestellungen für Tutoren

### ISSUE THREAD

**Issue by Pflegusch** [Philipp-g/muesli#27]
Intuitive Namen der Funktionen und Bedienelemente sowie etwaige Hilfestellungen zur Unterstützung der Tutoren sollen geboten werden. Die Funktionen sollten dokumentiert sein.

**Comment by julien789** [comment]
Sowohl für Tutoren, als auch für Studenten und Dozenten wurden Tooltips in Form von Hover-Tooltips und ausklappbaren Hilfeboxen implementiert. Diese Tooltips sind an entsprechenden Stellen in der Seite eingebaut, sodass man nicht auf eine Dokumentationsseite wechseln muss.

Alle Tooltip-Texte stehen in der Datei tooltips.py und können von dort aus verändert werden, ohne dass man den entsprechenden HTML-Tag finden muss. Dadurch kann auch leicht eine englische Version der Tooltips hinzugefügt werden, falls das Muesli irgendwann übersetzt werden soll.

Falls noch jemand Wünsche oder Ideen für weitere Tooltips hat, meldet euch bitte bei uns (Gui1).
