### ISSUE TITLE
Müsli als Tutor/Assistent aus Studisicht sehen

### ISSUE THREAD

**Issue by Pflegusch** [Philipp-g/muesli#28]
Der Tutor sollte eine Möglichkeit haben, dass Müsli aus der Sicht eines Studis zu sehen und wechseln zu können zwischen Tutor- und Studisicht. 

Muss dafür am Backend etwas geändert werden?

**Comment by DieGoldeneEnte** [comment]
So wie ich das sehe sollte es reichen den Server um eine bool-Variable zu erweitern, die an das Template übergeben wird. Dann reicht es nur die Templates zu ändern.
Das "backend change"-Label nehme ich mal wieder runter, da ich das als Hinweis (besonders für die API-Gruppe) angelegt habe, dass sich hier was ändert, was Änderungen an der API

**Comment by tynsh** [comment]
Ich hab diesen Änderungsvorschlag noch nicht bis zum Ände überlegt. Es könnte sein, dass es ausreicht in alle Templates einen Modus einzubauen, der Buttons der Dozenten deaktiviert und eine auffällige Leiste oben im Müsli einfügt, die darauf hinweist, dass man sich im Vorschaumodus befindet. Dozenten sollten sich aber nicht aus Versehen in Übungsgruppen anmelden können sollen. Das könnte man vmtl. mit etwas Javascript verhindern und stattdessen ein Popup anzeigen, dass die Aktion beschreibt, die nicht ausgeführt wurde (z.B. sich in eine Übunsgruppe eintragen).
