### ISSUE TITLE
Dozent Punkte der Klausur eintragen und Noten berechnen lassen

### ISSUE THREAD

**Issue by LikMaiDong69** [Philipp-g/muesli#29]
Der Dozent will die Punkte der Klausur eintragen und die Noten berechnen lassen.

**Comment by tynsh** [comment]
Geht es hierbei um die Preview Ansicht der Statistiken für eine nicht abgespeicherte Notenformel? Ich versteh nicht ganz was dieses Issue beschreibt.

**Comment by LikMaiDong69** [comment]
Siehe GUI540 in OneNote.
Hierbei geht es um das Eintragen der Punkte in eine bereits vorhandene Klausur und in direktem Anschluss um die entsprechende Berechnung der Noten.

**Comment by julien789** [comment]
Als Dozent erhält man jetzt nach dem berechnen der Noten, aber noch vor dem speichern, eine Vorschau der Noten in Form von einem Diagramm und einer Auflistung, die angibt wieviel Prozent der Klausurteilnehmer mindestens Note 1, 2, 3 und 4 haben.
