### ISSUE TITLE
Dozent Übungszettel anlegen Workflow

### ISSUE THREAD

**Issue by LikMaiDong69** [Philipp-g/muesli#30]
Ich möchte als Dozent Übungszettel anlegen (Workflow verbessern)

**Comment by tynsh** [comment]
Ich verstehe dieses Issue nicht. Kannst Du das bitte ausführen? Als Dozent kann man ja Übungszettel anlegen.

**Comment by LikMaiDong69** [comment]
Wie in der Beschreibung erwähnt, geht es hier um einen verbesserten Workflow. 
Aktuell ist das Anlegen der Übungszettel verbesserungsbedürftig. Es kann mit einer Umstrukturierung der Workflow verbessert werden.

**Comment by tynsh** [comment]
Ah, verstehe. Gibt es schon einen konkreten Verbesserungsvorschlag wie der Arbeitsablauf zum Erstellen von Übungszetteln verbessert werden soll bzw. wie umstrukturiert werden soll?
