### ISSUE TITLE
Dozent Daten ins Müsli importieren/exportieren

### ISSUE THREAD

**Issue by LikMaiDong69** [Philipp-g/muesli#31]
Der Dozent möchte Daten ins Müsli importieren oder exportieren (echte Exportfunktion, vermutlich Excel Format).

**Comment by tynsh** [comment]
Vielleicht würde sich hierfür eher CSV anbieten. Man kann aus vielen Programmen (unter Anderem Excel und LibreOffice Calc) CSVs erstellen. Wenn sich aber herausstellt, dass MS Excel Formate verwendet werden müssen, ist das auch in Ordnung. Man sollte nur darauf achten, dass man auch via LibreOffice Daten ins MÜSLI importieren kann.

**Comment by LikMaiDong69** [comment]
Die Diskussion über CSV gab es bereits kurz beim letzten Treffen. Excel ist aktuell vorgesehen.
Bezüglich der Kompatibilität zu LibreOffice stimme ich dir zu, jedoch nicht als muss, sondern optional als Bonus.
Man bedenke, dass Dozenten ohnehin Microsoft Office verwenden & höchstwahrscheinlich von der Universität kostenlos gestellt bekommen.

**Comment by DieGoldeneEnte** [comment]
> Man bedenke, dass Dozenten ohnehin Microsoft Office verwenden & höchstwahrscheinlich von der Universität kostenlos gestellt bekommen.
Die Angestellte der Universität bekommen eine Office/Windows Lizenz über das URZ.

Ich wäre auch für csv, aber ich glaube die meisten Professoren arbeiten immer mit LIbreoffice/Excel wenn es um Tabellen-Daten geht. Wir müssten also eine erklärung hinzufügen wie man das als csv importieren/exportieren kann.

**Comment by tynsh** [comment]
> Man bedenke, dass Dozenten ohnehin Microsoft Office verwenden & höchstwahrscheinlich von der Universität kostenlos gestellt bekommen.

Leider nicht. In der Informatik ist das zumindest halbwegs konsistent, in der Reinen Mathe dagegen gibt es auf den Arbeitsrechnern der Mitarbeiter, die sich in der Regel als Obertutoren ums MÜSLI kümmern, nicht mal MS Office.

Vielleicht kann man notfalls prüfen, ob man aus Libreoffice als xlsx exportierte Tabellen verwenden kann.
