### ISSUE TITLE
Workflow für Batch-Eingabe von Punkten entscheiden

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#39]
Es gab zwei verschiedene Vorschläge, wie man die Eingabe von Punkten (besonders in Bezug auf Abgabegruppen) verbessern kann. Hierbei muss beachtet werden, dass Übungsgruppen sich verändern können oder gegebenenfalls nicht fest sind, weshalb es keinen Sinn macht die Gruppen fest abzuspeichern.
Wir müssen uns auf einen Workflow einigen, der für möglichst viele Tutoren gut funktioniert. Wenn ihr andere Ideen/Vorschläge habt, hängt die einfach hier an.

**Comment by DieGoldeneEnte** [comment]
Vorschlag von Gui010:
Steps                                                         
    • Dafür möchte ich zuerst die Mitglieder der Zettelgruppe auswählen und dann die Punkte für deren aktuelle Abgabe eintragen. 
    • Während des Eintragens werden mit die ausgewählten Namen angezeigt. 
    • Danach sollen bei allen Mitgliedern der Abgabegruppe die Punkte eingetragen sein, sodass ich sie nicht redundant einzeln bei allen eintragen muss. 
    • Nach erfolgreichem Eintragen soll mir zurückgemeldet werden, dass die Punkte bei allen erfolgreich eingetragen wurden. 
    • Danach möchte ich zurück zur Hauptseite der Lehrveranstaltung oder direkt die Punkte für die nächste Gruppe eintragen.

**Comment by DieGoldeneEnte** [comment]
Vorschlag aus der ersten Muesli-Gruppen-Besprechung (ungenau, da das nirgendwo steht):
- Der Tutor gibt die Punkte für einen aus der Gruppe ein und Speichert diese.
- Der Tutor gibt für den nächsten aus der Gruppe die Punkte ein
- Die Felder sind automatisch mit den Punkten der letzten Eingabe gefüllt und werden geleert, sobald er ein Feld verändert

**Comment by OccamsBeard** [comment]
Zu den letzten beiden Vorschlägen
---
**Allgemein**
Ich würde die Leute aus folgenden Gründen **nicht persistent** (für das ganze Semester) in Zettelgruppen gruppieren:
* Abgabegruppen wechseln manchmal während des Semesters (weil z.B. Leute abspringen und sich Gruppen dann mit anderen zusammentun),
* Zu Beginn des Semesters wird oft in kleineren/anderen Gruppen abgegeben, als ab der zweiten oder dritten Woche, weil sich da noch nicht alle Zettelgruppen zusammengefunden haben,
* In einigen Fällen möchten Tutoren/Assistenten individuell Zusatzleistungen o.Ä. für nur eine Person aus der Zettelgruppe eintragen können, was bei persistenter Gruppierung schwierig wird.

**Vorschlag von Gui010** https://github.com/Philipp-g/muesli/issues/39#issuecomment-441581303
So würde ich das als Tutor machen wollen und *würde das auch als Entwickler so umsetzen*.
* Dabei wird also nur für den Nutzer sozusagen pseudogruppiert, damit er keine redundante Eingabe vornehmen muss, obwohl alle, die den Zettel zusammen abgeben, i.d.R. auch dieselben Punkte bekommen.

**Vorschlag aus der ersten Muesli-Gruppen-Besprechung** https://github.com/Philipp-g/muesli/issues/39#issuecomment-441582207
Dieses Vorgehen würde ich *nicht umsetzen*, weil:
* Das auf jeden Fall mindestens einige Nutzer verwirren kann,
* Man bei versehentlicher Übernahme der Punkte auf einen Nutzer einer anderen Abgabegruppe nur schwer (als Nutzer) nachvollziehen kann, ob die korrekte Anzahl Punkte eingetragen ist, oder nicht (zumindest ist das dann ziemlich nervig).

**Comment by tynsh** [comment]
Ich hab jemanden mit einer starken Meinung angeschrieben. Vielleicht kommentiert er dieses Issue noch.

Weiterer Vorschlag:

Es gibt derzeit eh 2 Modi zum Eintragen von Punkten. Man kann den Vorschlag aus der Vorbesprechung für die interaktive Eingabe von Punkten übernehmen. Für die normale Ansicht kann man das System der Physik übernehmen:

Anfangs hat man eine Tabelle mit folgenden Spalten:

- Name
- Punkte Aufgabe 1
- Punkte Aufgabe 2
- …

Man kann nun auf den Namen einer Person klicken und bekommt eine Auswahl einer anderen Person zur Abgabe. Diese Abgabegruppe wird eingerückt dargestellt. Punkte für die Abgabegruppe werden automatisch für alle TeilnehmerInnen übernommen, diese können aber anschließend von hand nochmal editiert werden um einer einzelnen Person andere Punkte vergeben zu können.

Diese Abgabegruppen bleiben über das Semester gespeichert, können aber jederzeit wieder geändert werden.

**Comment by DieGoldeneEnte** [comment]
>     * Dabei wird also nur für den Nutzer sozusagen pseudogruppiert, damit er keine redundante Eingabe vornehmen muss, obwohl alle, die den Zettel zusammen abgeben, i.d.R. auch dieselben Punkte bekommen.

Ich weiß nicht wie du dir das mit dem pseudogruppieren vorstellst und mir persönlich fällt auch keine besonders nutzerfreundliche Art ein das umzusetzen.
Ich kann mir die Arbeit Punkte einzutragen aber auch nicht wirklich vorstellen, da ich mir das nur angesehen habe mit 2 Übungsgruppen Teilnehmern.

**Comment by OccamsBeard** [comment]
> Ich weiß nicht wie du dir das mit dem pseudogruppieren vorstellst und mir persönlich fällt auch keine besonders nutzerfreundliche Art ein das umzusetzen.

Mir fallen da schon Varianten ein (siehe Mock-Ups). Mit pseudogruppieren (war vielleicht eine schlechte Wortwahl) meine ich, dass nur für den Nutzer gruppiert wird, aber nicht in den Daten.

![mockuppunkteeintragenbatch](https://user-images.githubusercontent.com/21686728/49020311-6c569b80-f190-11e8-830f-8bac98d6e559.png)

Nach dem Auswählen der Leute kämst du dann zum eigentlichen Punkte eintragen (kann man vielleicht auch auf einer Seite realisieren, ist nur ein erster Vorschlag):

![mockuppunkteeintragenbatch2](https://user-images.githubusercontent.com/21686728/49021182-58139e00-f192-11e8-8499-2b455357bb3f.png)

**Comment by OccamsBeard** [comment]
Dieses Issue ist verwandt mit einem Issue im "echten" MÜSLI-Repository: https://github.com/muesli-hd/muesli/issues/12.

**Comment by DieGoldeneEnte** [comment]
Der Workflow wird über ein Dropdown mit Suchleiste mithilfe von JQuery umgesetzt. Der Ablauf wird dem Vorschlag von OccamsBeard entsprechen.
