### ISSUE TITLE
Datenbank um Logging-Funktion erweitern

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#41]
Die Datenbank braucht um ein An- & Abmeldehistorie anzuzeigen die Möglichkeit Events abzuspeichern. Dafür müsste man eine neue Tabelle hinzufügen mit einem Schema, das z.B. folgende Attribute enthält:
- Vorlesungs ID
- Timestamp
- Event-Text

**Comment by tynsh** [comment]
Siehe #43 . Weiß nicht ob das wirklich sinnvoll ist.
