### ISSUE TITLE
Seite zum anzeigen der Logs erstellen

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#43]
Um die Logs einsehen zu können braucht es eine Seite,  auf der die Events zeitlich sortiert angezeigt werden.

**Comment by tynsh** [comment]
Ist das wirklich notwendig? Logs sind Datenschutztechnisch etwas kritisch. Bisher gab es außerhalb der Entwicklung keinen Grund zusätzliche Logs darüber zu speichern was NutzerInnen auf der Platform machen.

Übersehe ich da einen vernünftigen Use-Case?
