### ISSUE TITLE
Berechtigungen für Einsicht der Logs

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#44]
Es muss geklärt werden, wer Logs einsehen darf (eventuell müssen die Logs gefiltert werden). Ausserdem müssen die Berechtigungen im Müsli umgesetzt und enforced werden.

**Comment by tynsh** [comment]
Logs können wie bisher einfach ins stderr geschrieben werden. Im Testsystem tauchen sie dann meist auf der Konsole auf, im Produktivsystem in den auch derzeit existierenden Logdateien.
