### ISSUE TITLE
Umfang des Loggins

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#45]
?Sollen Logs erzeugt werden und wenn ja was soll gespeichert werden?
Die Logs sind nicht ganz unkritisch, was den Datenschutz angeht, entsprechend sollte vorher geklärt werden ob wir solche Daten überhaupt sammeln dürfen/sollen.

**Comment by tynsh** [comment]
Es sollten keine Logs außerhalb von exceptions angelegt werden. Falls es fürs debugging interessant ist, kann man einen debug flag hinzufügen, der im muesli-test.py Skript gesetzt wird und hiermit nicht in der Produktivversion enthalten ist.

**Comment by tynsh** [comment]
Okay, sorry. Hab ich übersehen. Ich nope die  Speicherung des Zeitpunktes der An/Abmeldung eines Studis.

Was ich cool fände, ist die Speicherung der Gesamtanzahl der Teilnehmer einer Vorlesung oder eines Tutoriums über die Zeit. Dabei sollte dies nur bis auf die Kalenderwoche genau gespeichert werden.

Neue Tabelle in der DB anlegen mit folgenden Infos:
- ÜG bzw. VL ID
- Kalenderwoche
- Teilnehmerzahl

Beispiel wenn sich ein Studi aus einer Übungsgruppe (ÜG) austrägt:

1. Studi aus ÜG austragen
2. Mail an TutorIn versenden
3. Prüfen ob in der Tabelle die aktuellste Woche der aktuellen entspricht.
  - Wenn ja, ändere den Eintrag der Teilnehmerzahl für diese Kalenderwoche dekrementieren
  - Wenn nein, neue Zeile anlegen für aktuelle Kalenderwoche und aktuelle Teilnehmerzahl eintragen.

**Comment by DieGoldeneEnte** [comment]
Ich habe das in #55, #56, #57 dargestellt, entsprechend fallen #41, #42, #43, 44 weg. Die Berechtigungen werden einfach per Übungsgruppe gehandhabt. So sollte dann jeder Tutor die Daten zu seinen Übungsgruppen sehen können.
