### ISSUE TITLE
[Api023] Als Assistent/Tutor Übersicht über meine API-Keys 

### ISSUE THREAD

**Issue by OccamsBeard** [Philipp-g/muesli#47]
Als Assistent/Tutor möchte ich die Möglichkeit haben eine Übersicht über meine API-Keys zu sehen.

**Comment by Philipp-g** [comment]
Aktueller Stand:
![image](https://user-images.githubusercontent.com/16564897/49235579-acb95200-f3fa-11e8-9c8c-ce1e4284ec95.png)

Ideen:
- Datum "kürzen" oder eventuell in Tage + Stunden umrechnen
- Scopes als Spalte
- Row eventuell rot hinterlegen wenn Key abgelaufen.
- Generate Key Form erstellen mit Dropdown Menu für Scopes & Laufzeit

**Comment by OccamsBeard** [comment]
* _Datum kürzen:_ Ja! _In Tage und Stunden umrechnen_ muss, finde ich **nicht unbedingt** sein.
* _Scopes als Spalte_ finde ich **gut**.
* _Row rot hinterlegen:_ **Ja!** Sollte aber noch irgendwo einen **Hinweis** "abgelaufen" enthalten. Eventuell mit ner Info, was der Nutzer dann tun soll (das ist für manche bestimmt nicht so offensichtlich wie für andere… ich denke da an so manche Obertutoren/Professoren)
* _Generate Key Form erstellen mit Dropdown Menu für Scopes & Laufzeit_: **Ja!**
* _Eventuell mit welchem Client der Key assoziiert ist??:_ Könnte man machen, vielleicht sollten wir da aber **noch mal überlegen**, ob die Zielgruppe für diese Ansicht diese Info überhaupt braucht.

**Comment by TheEbolaDoc** [comment]
Ich hab in der Zwischenzeit im Commit 9f45f41d313fc3773a713aba76c163578589c59a noch ein Feld "Beschreibung" hinzugefügt und das Datumsformatting verbessert 
Siehe:
![image](https://user-images.githubusercontent.com/26827864/49332751-fcdb1480-f5b2-11e8-8462-c4d82c8db25c.png)
