### ISSUE TITLE
Studenten über verschieben zwischen Übungsgruppen benachrichtigen

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#5]
Ein Student, der in eine andere Übungsgruppe verschoben wurde soll durch eine E-Mail benachrichtigt werden. Gegebenenfalls sollen auch betroffenen Tutoren (und der Professor?) benachrichtigt werden.

**Comment by tynsh** [comment]
Siehe #7

**Comment by tynsh** [comment]
Ah, ja. Das ist richtig. nvm.
