### ISSUE TITLE
Übersicht OAuth-Clients Admin-Interface

### ISSUE THREAD

**Issue by Philipp-g** [Philipp-g/muesli#58]
Als Admin sollte man eine Übersicht über alle OAuth Clients haben um ggf. Clients zu entfernen.
Da es vermutlich nicht mehr als eine handvoll  OAuth-Clients geben wird (1 für muesli eigene API keys, 1 für eine App???, etc.) wäre es vielleicht auch sinnvoll das erstellen der Clients manuell über das Admin Interface zu machen und das nicht automatisch zu tun.

**Comment by tynsh** [comment]
Das klingt gut, allerdings könnte man das Anzeigen von API keys auf 2 verschiedene Seiten verteilen:

1. als Admin kann man auf die Seite "Nutzerliste" unter "Administration" zugreifen. Wenn man auf einen Nutzer klickt, können auf der Informationsseite des Nutzers die API Keys stehen. Dies ist die gleiche Seite, wie für den Nutzer selber, wenn sie oder er die eigenen Keys ansehen möchte.
2. Systemweite API keys benötigen eine separate Übersichtsseite. Wir verwenden das Beispiel des Keys für MaMPf. Dieser Key sollte ~5 Jahre lang gültig sein und besondere Schreibrechte bekommen. Man sollte ihn auf dieser Seite generieren und löschen können.

Allgemeine Dinge:
- API Keys dürfen nur die Berechtigungen des Nutzers erhalten, der sie erstellt hat (Ausnahme sind systemweite Keys).
- Keys sind immer zusammen mit einem Namen anzulegen. Beispielsweise "My awesome Android App 1", die für den Nutzer eindeutig sind. Wenn die gleiche awesome app auf einem anderen Gerät verwendet wird, erstellt diese einfach mit Hilfe des Nutzernamens und Passworts einen neuen Key mit einer 2, statt der 1 am Ende des Namens.
- Es sollte eine einfache URL zum automatischen Anlegen eines Keys geben. Beispielsweise sollte die Awesome App bei der ersten Verwendung den Nutzernamen und das Passwort des Nutzers abfragen und mit Hilfe dieser beispielsweise unter https://muesli.….de/request_api_key?email=kevin@example.com&password=mysecretpw einen Key bekommen
- In jeglichen Listen sollten nur die Namen der Keys sichtbar sein. Die Keys selber sollten nicht angezeigt werden.

Ich hoffe das hilft weiter. Wenn es andere Ideen gibt, immer her damit :-)

**Comment by TheEbolaDoc** [comment]
Nachdem wir von OAuth2 auf JWT-Tokens umgestiegen sind erübrigt sich dieses Issue eigentlich.

Im Admin interface ist es jetzt aber möglich die Tokens eines Users zu sehen (Nutzerliste).
Der Bereich wird nur eingeblendet, falls der User über Tokens verfügt, wie es auch bei den anderen Ansichten dort der Fall ist.
Die Funktion um Keys zu erstellen ist hier entfernt.
