### ISSUE TITLE
Benachrichtigungen für verschieben einstellbar machen

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#6]
?Wollen wir das wirklich einstellbar haben?
Die Oberfläche ist zur Zeit ein Dropdown und ein Button in einer Tabelle. Für diese Funktion müsste man diese Funktionalität verschieben (ich würde auf eine eigene Seite vorschlagen).

Dem Tutor soll die Möglichkeit gegeben werden einzustellen, wer eine Benachrichtigng bekommen, wenn er einen Studenten in eine andere Übungsgruppe verschiebt,

Mögliche Addressaten:
- Der Tutor aus dem der Student verschoben wird
- Der Tutot zu dem der Student verschoben wird
- Der Student der verschoben wird
- Der Professor der Vorlesung?

**Comment by tynsh** [comment]
Wenn #7 eh wegfällt, kann man auch das weglassen.
