### ISSUE TITLE
Dinge die man vor dem PR wieder zurückrollen muss

### ISSUE THREAD

**Issue by TheEbolaDoc** [Philipp-g/muesli#60]
In diesem issue sollten Dinge stehen, die man ändern muss bevor zurück ins "echte" Müsli gemerged werden kann:
- [ ] change `docker-compose.yml` to use the SQL file `travis-muesli-origDb.sql`
- [ ] remove the `api.sql` file
- [ ] (remove `**/Session.vim` from the `.gititnore`

**Comment by Philipp-g** [comment]
- [ ] https://github.com/Philipp-g/muesli/commit/f0b856467fd91271bc5ccece0072f50e31171a1d reverten oder alternativ `productive` auf True setzen

**Comment by TheEbolaDoc** [comment]
- [ ] change `JWT_SECRET_TOKEN` to something reasonably long / safe

`./docker-compose.yml`:
```
[...]
    environment:
      - JWT_SECRET_TOKEN=secret
[...]
```

**Comment by TheEbolaDoc** [comment]
- [ ] change `MAX_KEYS` in `./muesli.yml` to an appropiate value
