### ISSUE TITLE
Filtering für API Requests

### ISSUE THREAD

**Issue by Philipp-g** [Philipp-g/muesli#64]
Es wäre vielleicht ganz sinnvoll wenn man Filtering für API Requests hätte.
Nützlicher Artikel dazu:
https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/

Mögliche Umsetzung:

`self.request.params` gibt einem ein [NestedMultiDict](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.IMultiDict) aus dem man dann ganz einfach die Parameter auslesen kann. Die Parameter müssen dann auf validiert werden und können dann in die DB query als filter genommen werden beispielsweise so `.filter(models.Lecture.id == self.params['id'])` . Wobei man sich hier überlegen muss wie man am besten über mehrere Parameter filtert. (bin mir sicher das SQLAlchemy hierzu etwas passendes hat. Einfach mal in der Doku lesen)

Beispiel Umsetzung an Lectures Collection:
```
if(not self.request.params):
            lectures = (
                self.db.query(models.Lecture)
                .options(joinedload(models.Lecture.assistants))
                .filter(models.Lecture.is_visible == True)
                .all()
            )
else:
            # TODO Parameter überprüfen
            lectures = (
                self.db.query(models.Lecture)
                .options(joinedload(models.Lecture.assistants))
                .filter(models.Lecture.is_visible == True)
                .filter(models.Lecture.id == self.request.params['id'])
                .all()
            )
```

**Comment by tynsh** [comment]
Das klingt super! Ich würde die Filterung jedoch etwas anders implementieren:

    allowed_filter_attributes = ['id', 'name', 'type', 'term', 'lsf_id', 'url']
    
    def apply_requested_api_filters(query, targetclass, request):
        partly_filtered_query = query
        for attribute in allowed_filter_attributes:
            if attribute in self.request.params:
                partly_filtered_query = partly_filtered_query.filter(getattr(targetclass, attribute) == self.request.params[attribute])

    lectures = (
                self.db.query(models.Lecture)
                .options(joinedload(models.Lecture.assistants))
                .filter(models.Lecture.is_visible == True)
            )
    return apply_requested_api_filters(lectures, self.Lecture, request).all()

Das ist ungetestet, aber sollte eine Richtung geben. Damit sind die zugelassenen Attribute sauber ausgegliedert und die unleserliche Funktion apply_requested_api_filters kann mehrfach verwendet werden. Falls ich etwas übersehen hab, sagt Bescheid. Der Vorteil dieses Designs ist auch, dass man bei der Definition des querys, in diesem Fall lectures, bereits vorauswählt, auf welche Daten ein Nutzer überhaupt zugreifen kann. Danach wird diese vorausgewählte Menge durch die Filter des Nutzers weiter eingeschränkt. Somit können schwieriger Sicherheitslücken entstehen :-)

**Comment by Philipp-g** [comment]
Verstehe deinen Gedanken wegen den Sicherheitslücken aber es werden eh vor der Rückgabe alle unerlaubten Attribute aus dem Objekt entfernt wie man hier sieht:
https://github.com/Philipp-g/muesli/blob/ca13f32e406080b1dbe7a7c94eaa06c20bd04444/muesli/web/api/viewsLecture.py#L27-L29
Aber es ergibt wahrscheinlich trotzdem Sinn die Inputparameter noch zusätzlich zu validieren.

**Comment by Philipp-g** [comment]
Mir ist beim Doku lesen von cornice noch das hier aufgefallen https://cornice.readthedocs.io/en/latest/api.html#cornice.validators.marshmallow_querystring_validator
Da müsste man mal schauen wie das implementiert ist da die Doku da nicht soviel zu sagt. Könnte aber nützlich sein.
