### ISSUE TITLE
[API] Authentifizierung durch JWT Tokens

### ISSUE THREAD

**Issue by Philipp-g** [Philipp-g/muesli#74]
Als Alternative für OAuth werden jetzt JWT Tokens für die Authentifizierung mit der API benutzt.
Das funktioniert seit https://github.com/Philipp-g/muesli/commit/d9132419646628c15f025af21fedbe67e7e47465 auch schon. Leider ist es mit dem aktuellen Rechtesystem des mueslis allerdings nicht sinnvoll machbar die Berechtigungen auf den Key zu übertragen. D.h. ein Key hat die gleichen Rechte wie der Nutzer welcher ihn generiert und dies lässt sich nicht weiter einschränken.

Ich würde das Issue hier als "Brainstorming Issue" für den Umgang mit den JWT Tokens betrachten.

Ideen:
- JWT Tokens eine sinnvolle Laufzeit geben. (wie lange)
  - Die Laufzeit wird jetzt aus der config ausgelesen und ist auf 30 Tage gesetzt.(c809a3823f5d067896807f394504059ce512736f)
- JWT Tokens in der API Übersicht generieren lassen
- Refresh von Tokens?
- Zugriff auf die API Übersicht nur für bestimmte Leute oder alle? (mit Tobias absprechen)

**Comment by DieGoldeneEnte** [comment]
So wie ich das interpretiere, kann man die Rechte etwas modularer abfragen, aber bei meinen Erweiterungen bin ich auf folgende Zeile gestoßen:
`self.request.permissionInfo.has_permission('enter_points')`(viewExam.py in EnterPointsBasic)
Ich interpretiere das so, dass man es zumindest etwas weiter eingrenzen kann. Ich kann aber natürlich nicht beurteilen wie das in eure API-Anfragen passt ;)
Vielleicht hilft euch das ja.

**Comment by Philipp-g** [comment]
Das Problem mit dem Rechte abfragen ist das die Permissions erst wenn ein request ankommt gesetzt werden. Ich wüsste also nicht wie man allgemein von einem Nutzer alle Berechtigung bekommen könnte ohne die context.py komplett neu zuschreiben
https://github.com/Philipp-g/muesli/blob/1b395ecff74baee62c461cf9212223b69cd02b32/muesli/web/context.py#L58-L63

**Comment by DieGoldeneEnte** [comment]
Das weiß ich auch nicht, dachte nur, dass man das für die weitere Einschränkung verwenden kann. Eine Möglichkeit wäre gegebenenfalls die Berechtigung beim Erstellen des Schlüssel abzufragen, also beim anfragen des Schlüssels auf eine Seite leiten, für die man die Rechte braucht? Dann könnte man die Rechte an die Tokens binden.
Ich brauche das zum Glück nicht, habe mich also nicht so genau damit befasst.

**Comment by Philipp-g** [comment]
Ja das könnte man tun das Problem ist nur das man nicht auf eine Seite leiten müsste sondern auf **alle** um herauszufinden welche Berechtigungen vorliegen und das ist nicht machbar. Und da die API Endpoints nicht genau die aktuellen Seiten wiederspiegeln sondern eher die Ressourcen dahinter würde das selbst wenn man es macht auch nicht so viel helfen.
