### ISSUE TITLE
Dokumentation der API

### ISSUE THREAD

**Issue by TheEbolaDoc** [Philipp-g/muesli#75]
Wie in der Präsentation am Anfang festgelegt, sollten wir eine sinnvolle Dokumentation der API bereitstellen. Da dies aktuell noch nicht passiert ist sollten wir damit bei [Zeit anfangen](https://image.slidesharecdn.com/stg206-161218200945/95/aws-reinvent-2016-case-study-how-spokeo-improved-web-application-response-times-with-amazon-efs-stg206-32-638.jpg?cb=1482091831).

Es wurde sich über folgende Möglichkeiten der Dokumentation Gedanken gemacht: 

### 1. Ein GitHub Wiki
- prinzipiell praktisch & schön
- schlecht zu maintainen & bindet an GitHub (/ Microsoft)

### 2. [https://github.com/ergo/pyramid_apispec](url) <-- ausgewählt
- Documentation in Code
- gut zu maintainen
- flexibel
- anstrengend aufzusetzen

### 3. Eine Seite im Projekt selbst
- schlecht zu maintainen 
- nicht schön
- müllt das Webinterface zu

## Was bisher schon passiert ist
- [x] installieren der benötigten Pakete in der `./requirements.txt`

- [x] verlinkung im "API-Keys"-Reiter

- [x] hacky Lösung für das Funktonieren mit `cornice` gefunden:
https://github.com/zerotired/pyramid_apispec/blob/6720483255706aca8057eb39f8dc4073b589b7da/pyramid_apispec/helpers.py#L136-L138

## Was noch zu tun ist
- [x] Die ausgebranchte Änderung in `api` übernehmen
- [x] Sobald er gemerged ist [diesen Pullrequest](https://github.com/ergo/pyramid_apispec/pull/10) verwenden und die hacky Lösung entfernen
- [x] Dokumentation für die API-Features vorantreiben
- [x] Gedanken über die Ausgabe der Doku machen ([widdershins](https://github.com/Mermade/widdershins) / [swagger-ui](https://swagger.io/tools/swagger-ui/))

**Comment by TheEbolaDoc** [comment]
Der letze PR wurde zwar nur geclosed, allerdings hat @ergo das mit einer selbst-Implementierung in Version `0.3.1` gefixt.

**Comment by ergo** [comment]
Guys I don't know German ;)

**Comment by TheEbolaDoc** [comment]
Oh im sorry, I just told them that one of our Todos (Make use of the PR 10 ( the one you recently closed) to remove a hacky intermediate solution) is done because even though you couldnt merge itthe initial problem is now fixed in the recent version... :smile: 

Thank you for your cool pyramid extension and sorry for disturbing :P 
Have a nice weekend
Chris

**Comment by ergo** [comment]
No problem, I didn't have time to write test for that and I wanted to push new release asap. Please confirm if this is fixed properly. Thanks.

**Comment by TheEbolaDoc** [comment]
For us it works perfectly fine!  :heart: 
If not I will open up an issue on your repo .. :grinning: 

![image](https://user-images.githubusercontent.com/26827864/52154292-7eb3f080-267d-11e9-8d2b-960ab7c99948.png)
