### ISSUE TITLE
"Testat Hinzufügen" besser formulieren

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Philipp-g/muesli#9]
Über den Link "Testat Hinzufügen" unter Testate bei einer Vorlesung kann man zur Zeit folgendes Hinzufügen:
- Übungszettel
- Klausur
- Praktische Übung
- Präsenzübung
- Probeklausur

Den Link sollte man umbenennen und vielleicht kann man auch Klausur/Probeklausur extra setzen.

Ich würde vorschlagen, das nach "Übungen hinzufügen" mit:
- Übungszettel
- Praktische Übung
- Präsenzübung

und "Klausur hinzufügen" mit:
- Klausur
- Probeklausur
aufzuteilen mit jeweils dem Ersten als Default.

**Comment by tynsh** [comment]
Hmm, bei der automatischen Vergabe von Noten auf Basis einer Formel muss man (in der Formel) sowohl auf Übungszettel, als auch auf Klausuren zugreifen können.

Ich finde die Änderung gut, allerdings sollte man oben genanntes immernoch ermöglichen und dies auf der Seite mit der Formel erklären.

Außerdem würde ich sowohl bei „Übungen hinzufügen“, als auch „Klausur hinzufügen“ einen Button „Sonstiges“ hinzufügen um einen beliebigen Typen angeben zu können. Der neue Typ muss dann aber auch in der db gespeichert werden. Dieses feature kann aber fürs erste weggelassen werden. Man kann wieder darauf zurückkommen.

**Comment by DieGoldeneEnte** [comment]
Der Vorschlag würde nur die Templates verändern und die Verlinkung zwischen den Seiten. So wie ich mir das vorstelle, kann man dann im Dropdown immernoch zwischen Probeklausur und Klausur (bzw. Übungszettel, Praktische Übung, Präsenzübung) wählen.
Der Pythoncode wird dadurch kaum verändert. Für die Benotung sollte es also keine Unterschiede geben.

Bezüglich der beliebigen Typen müsste man sich überlegen wie man die auf der Seite darstellen will und wie man das am Besten in der Datenbank darstellt. Wenn wir das machen wollen sollten wir das möglichst früh machen, damit das auch in die API eingegliedert werden kann.

**Comment by tynsh** [comment]
Ich hab mich entschieden. Wir lassen diese Eingabe „Sonstige“ weg. Es lohnt sich nicht. Man kann jederzeit einen weiteren Prüfungstyp mit einem neuen Identifier hinzufügen.
